### ISSUE TITLE
Job Deletion Issues

### ISSUE THREAD

**Issue by vikramalva** [proteinevolution/Toolkit#1151] opened 2020-11-16 15:06 UTC
- [ ] rework delete in job actor (use flag for different modes, don't qdel for scheduled sweep, allow lists?)
- [x] display loading on job submit

**Comment by zy4** [comment] 2020-11-25 08:39
can you be more specific, @vikramalva ?

**Comment by felixgabler** [comment] 2020-11-25 09:33
the issue is that on each unused job sweep, the toolkit slows down dramatically. No new jobs can be submitted and duplicates are created if one tries to submit them (this part can be fixed by displaying loading after submit in frontend).
However, we would like to fix the underlying issue in the backend. 
For one, the cleanup method does not need to call the delete.sh script. This is only necessary for manual deletion of jobs.
Moreover, we send too many events to the one job actor and this could probably be grouped into one delete event that receives an array of job ids as input. What do you think about that?

**Closed** 2021-01-03 09:37 UTC
Labels: bug
